### ISSUE TITLE
ERROR in Error encountered resolving symbol values statically. Function calls ar e not supported. Consider replacing the function or lambda with a reference to a n exported function 

### ISSUE THREAD

**Issue by smile2014** [whoissj/ng4-admin#1]
ERROR in Error encountered resolving symbol values statically. Function calls ar
e not supported. Consider replacing the function or lambda with a reference to a
n exported function (position 194:50 in the original .ts file), resolving symbol
 NgModule in E:/ng4-admin-master/node_modules/ng-zorro-antd/node_modules/@angula
r/core/core.d.ts, resolving symbol NgZorroAntdModule in E:/ng4-admin-master/node
_modules/ng-zorro-antd/src/release/ng-zorro-antd.module.d.ts, resolving symbol N
gZorroAntdModule in E:/ng4-admin-master/node_modules/ng-zorro-antd/src/release/n
g-zorro-antd.module.d.ts

**Comment by whoissj** [comment]
每次第一次编译的时候会报这个错，在app.module.ts的@NgModule，imports里把NgZorroAntdModule.forRoot()先注释掉，编译成功之后再把注释取消，这样又可以了。

**Comment by whoissj** [comment]
这是ng-zorro的bug,看下这个
https://github.com/NG-ZORRO/ng-zorro-antd/issues/23

**Comment by smile2014** [comment]
谢谢了，已经OK了
